#EQEmu Public Login Server OPCodes
# Opcode values are the client's logical values. EQ application opcodes are
# serialized little-endian by the RDP stream.
OP_SessionReady=0x0059
OP_LoginOSX=0x008e
OP_LoginPC=0x0001
OP_ClientError=0x0002
OP_LoginDisconnect=0x0005
OP_ServerListRequest=0x0046
OP_PlayEverquestRequest=0x0047
OP_LoginUnknown1=0x0048
OP_LoginUnknown2=0x004A
#OP_PlayEverquestResponse=0x0021
#OP_ChatMessage=0x0016
OP_LoginAccepted=0x0004
OP_LoginComplete=0x0088
OP_ServerName=0x0049
OP_LoginBanner=0x0052
#OP_ServerListResponse=0x004a
#OP_Poll=0x0029
#OP_EnterChat=0x000f
#OP_PollResponse=0x0011
